//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniPrj_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonnement
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_debut { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> idTrajet { get; set; }
        public Nullable<double> tarif { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Trajet Trajet { get; set; }
    }
}
